{% set name = "stanio" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 348d52f947dec431e118f4b601c4c5296929b86401d4d4dd5aa9373b0d4ae4ac
  - url: https://github.com/stan-dev/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: fd7b0788d9ac67fb0a9ee9d489f87ed5f2abd272864499a71054c94776d3b50d
    folder: gh_src

build:
  number: 2
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - numpy
  run_constrained:
    - ujson >=5.5.0

test:
  source_files:
    - gh_src/test
  imports:
    - stanio
  requires:
    - pip
    - pytest
    - pandas
  commands:
    - pip check
    - pytest -v gh_src/test

about:
  home: https://github.com/WardBrian/stanio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Preparing inputs to and reading outputs from Stan.
  description: Preparing inputs to and reading outputs from Stan.
  doc_url: https://github.com/WardBrian/stanio
  dev_url: https://github.com/WardBrian/stanio

extra:
  recipe-maintainers:
    - WardBrian
